<?php
/** @var MyParcelNL\Magento\Block\Sales\NewShipment $block */

use MyParcelNL\Sdk\src\Model\Consignment\AbstractConsignment;
use MyParcelNL\Magento\Model\Sales\MagentoOrderCollection;

$magentoOrderCollection = new MagentoOrderCollection();
?>
<input name="mypa_extra_options_checkboxes_in_form" value="1" type="hidden" /><!-- MyParcel options -->
<div class="field choice admin__field admin__field-option field-mypa_create_from_observer mypa_create_from_observer-toggle">
    <input
        id="mypa_create_from_observer"
        class="admin__control-checkbox"
        name="mypa_create_from_observer"
        value="1"
        type="checkbox"
        checked="checked" />
    <label class="admin__field-label" for="mypa_create_from_observer">
        <span><?= ($magentoOrderCollection->isOrderManagementEnabled()) ? __('Export Entire Order') : __('Create MyParcel consignment') ?></span>
    </label>
</div>
<?php
foreach ($block->getNewShipmentForm()->getCarrierSpecificAbstractConsignments() as $abstractConsignment) {
    $carrier      = $abstractConsignment->getCarrier();
    $carrierName  = $carrier->getName();
    $carrierHuman = $carrier->getHuman();
    ?>
    <div class="field field-mypa_carrier_<?= $carrierName ?> mypa_carrier-toggle js--mypa-options" style="margin-top:
    10px;">
        <div class="admin__field-control">
            <div class="admin__field admin__field-option">
                <input
                    type="radio"
                    class="admin__control-radio"
                    id="mypa_carrier_<?= $carrierName ?>"
                    name="mypa_carrier"
                    value="<?= $carrierName ?>">
                <label class="admin__field-label" for="mypa_carrier_<?= $carrierName ?>"><?= __(
                        $carrierHuman
                    ) ?></label>
            </div>
        </div>
    </div>
    <div
        class="field field-mypa_package_type js--mypa-options"
        data-for_mypa_carrier="<?= $carrierName ?>"
        style="margin: 10px 0 0 30px;">
        <div class="admin__field-control">
            <?php
            $country = $block->getCountry();
            foreach ($abstractConsignment->getAllowedPackageTypes() as $packageTypeName) {
                $packageTypeId = AbstractConsignment::PACKAGE_TYPES_NAMES_IDS_MAP[$packageTypeName];
                if (AbstractConsignment::CC_NL !== $country
                    && in_array($packageTypeId, [
                        AbstractConsignment::PACKAGE_TYPE_DIGITAL_STAMP,
                        AbstractConsignment::PACKAGE_TYPE_MAILBOX,
                    ], true)) {
                    continue;
                }
                $packageTypeHuman = $block->getNewShipmentForm()::PACKAGE_TYPE_HUMAN_MAP[$packageTypeId]
                    ??
                    $packageTypeName;
                ?>
                <div class="admin__field admin__field-option">
                    <input
                        type="radio"
                        class="admin__control-radio"
                        id="mypa_package_type-<?= $packageTypeName ?>_<?= $carrierName ?>"
                        name="mypa_package_type"
                        value="<?= $packageTypeName ?>">
                    <label
                        class="admin__field-label"
                        for="mypa_package_type-<?= $packageTypeName ?>_<?= $carrierName ?>"><?= __(
                            $packageTypeHuman
                        ) ?></label>
                    <?php
                    if (AbstractConsignment::PACKAGE_TYPE_DIGITAL_STAMP === $packageTypeId) {
                        $weight = $block->getDigitalStampWeight(); ?>
                        <span data-for_mypa_package_type="<?= $packageTypeName ?>">
                            <select
                                name="mypa_digital_stamp_weight"
                                id="mypa_digital_stamp_weight_<?= $carrierName ?>"
                                class="required product-custom-option admin__control-select"
                                style="margin: 10px 0 0 30px"
                                title="">
                                <option value="0">No standard weight</option>
                                <option
                                    value="20" <?= '20' === $weight
                                    ? 'selected="selected"'
                                    : '' ?> >0 - 20 gram
                                </option>
                                <option
                                    value="50" <?= '50' === $weight
                                    ? 'selected="selected"'
                                    : '' ?> >20 - 50 gram
                                </option>
                                <option
                                    value="100" <?= '100' === $weight
                                    ? 'selected="selected"'
                                    : '' ?> >50 - 100 gram
                                </option>
                                <option
                                    value="350" <?= '350' === $weight
                                    ? 'selected="selected"'
                                    : '' ?> >100 - 350 gram
                                </option>
                                <option
                                    value="2000" <?= '2000' === $weight
                                    ? 'selected="selected"'
                                    : '' ?> >350 - 2000 gram
                                </option>
                            </select>
                        </span>
                        <?php
                    } // end only digital stamp
                    ?>
                </div>

                <?php
                $carrier = $abstractConsignment->getCarrier();
                if (! $carrier) {
                    continue;
                }
                $carrierName = $carrier->getName();
                ?>
                <div
                    class="field choice admin__field admin__field-option field-mypa_label_amount mypa_package-toggle
    mypa-option-toggle" style="padding-left: 30px;" data-for_mypa_package_type="<?= $packageTypeName ?>">
                    <label
                        class="admin__field-label"
                        for="mypa_label_amount_<?= $carrierName ?>_<?= $packageTypeId ?>"
                        style="display: block">
                        <span><?= __('Label amount:') ?></span>
                    </label>
                    <?php $label_amount = 1; ?>
                    <select
                        name="mypa_label_amount"
                        id="mypa_label_amount_<?= $carrierName ?>_<?= $packageTypeId ?>"
                        class="required product-custom-option admin__control-select"
                        title="">
                        <?php
                        while ($label_amount <= 10) {
                            echo '<option value="' . $label_amount . '" >' . __($label_amount) . '</option>';
                            $label_amount++;
                        }
                        ?>
                    </select>
                </div>
                <?php
                if (AbstractConsignment::CC_NL !== $block->getCountry()) {
                    continue;
                }

                try {
                    $abstractConsignment->setPackageType($packageTypeId);
                } catch (\Exception $e) {
                    continue;
                }
                foreach ($abstractConsignment->getAllowedShipmentOptions() as $shipmentOption) {
                    if (AbstractConsignment::SHIPMENT_OPTION_INSURANCE === $shipmentOption
                        || ! $abstractConsignment->canHaveShipmentOption($shipmentOption)) {
                        continue;
                    }
                    $isActive = ($abstractConsignment::SHIPMENT_OPTION_LARGE_FORMAT === $shipmentOption)
                        ? $block->hasDefaultLargeFormat($shipmentOption, $carrier->getName())
                        : $block->hasDefaultOption($shipmentOption, $carrier->getName());
                    ?>
                    <div
                        class="field choice admin__field admin__field-option field-mypa_signature mypa_package-toggle mypa-option-toggle"
                        data-for_mypa_package_type="<?= $packageTypeName ?>"
                        style="padding-left:30px;">
                        <input
                            id="mypa_<?= $shipmentOption ?>_<?= $carrierName ?>_<?= $packageTypeId ?>"
                            class="admin__control-checkbox"
                            name="mypa_<?= $shipmentOption ?>"
                            value="1"
                            type="checkbox"
                            <?= $isActive
                                ? 'checked="checked"'
                                : '' ?>
                        />
                        <label
                            class="admin__field-label"
                            for="mypa_<?= $shipmentOption ?>_<?= $carrierName ?>_<?= $packageTypeId ?>">
                            <span><?= $block->getNewShipmentForm()
                                          ->getShipmentOptionsHumanMap()[$shipmentOption] ?? $shipmentOption ?>
                            </span>
                        </label>
                    </div>

                    <?php
                }

                if ($abstractConsignment->canHaveShipmentOption(AbstractConsignment::SHIPMENT_OPTION_INSURANCE)) {
                    ?>
                    <div
                        class="field choice admin__field admin__field-option field-mypa_insurance mypa_package-toggle mypa-option-toggle"
                        data-for_mypa_package_type="<?= $packageTypeName ?>"
                        style="padding-left:30px;">
                        <label class="admin__field-label" for="mypa_insurance" style="display: block">
                            <span><?= __('Insured up to:') ?></span>
                        </label>
                        <?php $defaultInsurance = $block->getDefaultInsurance($carrier->getName()); ?>
                        <select
                            name="mypa_insurance"
                            id="mypa_insurance"
                            class="required product-custom-option admin__control-select"
                            title="">
                            <option value="0"><?= __('No insurance') ?></option>
                            <?php
                            foreach ($abstractConsignment->getInsurancePossibilities() as $insurancePossibility) {
                                printf(
                                    '<option value="%1$s" %2$s>€ %1$s</option>',
                                    $insurancePossibility,
                                    $insurancePossibility === $defaultInsurance
                                        ? 'selected="selected"'
                                        : ''
                                );
                            }
                            ?>
                        </select>
                    </div>

                    <?php
                } // end can have insurance
            } // end foreach packageType
            ?>
        </div>
    </div>
    <?php
} // end foreach carrier
?>
<script type="text/x-magento-init">
{
    ".page-footer": {
        "myparcelnl_newshipment": {
            "carrier": "postnl",
            "packageType":"<?= array_flip(AbstractConsignment::PACKAGE_TYPES_NAMES_IDS_MAP)[$block->getPackageType()] ?>"}
    }
}
</script>
