<?php /** @var $block \MyParcelNL\Magento\Block\Sales\OrdersAction */ ?>
<script type="text/x-magento-init">
   {
       ".page-footer": {
           "myparcelnl_massaction": {
                "has_api_key": "true",
                "url": "<?= $block->getOrderAjaxUrl() ?>",
                "url_options_form": "<?= $block->getOptionsFormUrl() ?>",
                "url_options_save": "<?= $block->getOptionsSaveUrl() ?>",
                "id_type": "order",
                "grid_data_source": "<?= $block->getGridDataSource() ?>",
                "settings": <?= $block->getPrintSettings() ?>,
                "button_present": false,
                "action_options": {
                    "request_type": true,
                    "package_type": true,
                    "print_position": true,
                    "label_amount": true,
                    "carrier": true
                }
           }
        }
   }
</script>
