<?php /** @var $block \MyParcelNL\Magento\src\Block\Sales\OrdersAction */ ?>
<script type="text/x-magento-init">
   {
       ".page-footer": {
           "myparcelnl_massaction": {
                "has_api_key": "true",
                "url": "<?= $block->getOrderAjaxUrl() ?>",
                "settings": <?= $block->getPrintSettings() ?>,
                "button_present": false,
                "action_options": {
                    "request_type": true,
                    "package_type": true,
                    "print_position": true,
                    "label_amount": true,
                    "carrier": true
                }
           }
        }
   }
</script>
