<?php /** @var $block \MyParcelNL\Magento\src\Block\Sales\OrderAction */ ?>
<script type="text/x-magento-init">
   {
       ".page-footer": {
           "myparcelnl_massaction": {
                "has_api_key": "true",
                "url": "<?= $block->getOrderAjaxUrl() ?>",
                "url_send_return_mail": "<?= $block->getAjaxUrlSendReturnMail() ?>",
                "settings": <?= $block->getPrintSettings() ?>,
                "button_present": true,
                "button_send_return_mail_present": true,
                "number_of_positions" : <?= $block->getNumberOfPrintPositions() ?>,
                <?php if ($block->canShip()): ?>
                    "action_options": {
                        "request_type": true,
                        "package_type": true,
                        "print_position": <?= $block->isToRowCountry() ? 'false' : 'true' ?>,
                        "label_amount": false
                    }
                <?php else: ?>
                    "action_options": {
                        "request_type": false,
                        "package_type": false,
                        "print_position": true,
                        "label_amount": true
                    }
                <?php endif; ?>
           }
       }
   }
</script>
