<?php

declare(strict_types=1); /* @var \MyParcelNL\Magento\Block\System\Config\Form\SettingsButton $block */

use Magento\Framework\Exception\LocalizedException;
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

  jQuery('#settings-button').click(function () {
    const params = {};
    console.log('<?php echo $block->getAjaxUrl() ?>')
    new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
      parameters:     params,
      loaderArea:     false,
      asynchronous:   true,
      });
    });
    });
</script>

<?php
try {
    echo $block->getButtonHtml();
} catch (LocalizedException $e) {
    echo $e->getMessage();
} ?>
