<?php

declare(strict_types=1);

/** @var \MyParcelNL\Magento\Block\Sales\ShipmentsAction $block */ ?>
<script type="text/x-magento-init">
   {
       ".page-footer": {
           "myparcelnl_massaction": {
                "has_api_key": "true",
                "url": "<?= $block->getShipmentAjaxUrl() ?>",
                "url_options_form": "<?= $block->getOptionsFormUrl() ?>",
                "url_options_save": "<?= $block->getOptionsSaveUrl() ?>",
                "id_type": "shipment",
                "grid_data_source": "<?= $block->getGridDataSource() ?>",
                "settings": <?= $block->getPrintSettings() ?>,
                "button_present": false,
                "action_options": {
                    "request_type": true,
                    "package_type": true,
                    "print_position": true,
                    "label_amount": true
                }
           }
        }
   }
</script>
