<?php /** @var $block \MyParcelBE\Magento\Block\Sales\ShipmentAction */ ?>
<script type="text/x-magento-init">
   {
       ".page-footer": {
           "myparcelbe_massaction": {
                "has_api_key": <?= $block->hasApiKey();?>,
                "entity_id": <?= $block->getEntityId();?>,
                "url": "<?= $block->getShipmentAjaxUrl(); ?>",
                "url_send_return_mail": "<?= $block->getAjaxUrlSendReturnMail(); ?>",
                "settings": <?= $block->getPrintSettings(); ?>,
                "button_present": true,
                "button_send_return_mail_present": false,
                "number_of_positions" : <?= $block->getNumberOfPrintPositions(); ?>,
                <?php if ($block->hasTrack() == false): ?>
                    "action_options": {
                        "request_type": true,
                        "package_type": true,
                        "print_position": <?= $block->isCdCountry() == true ? 'false' : 'true'; ?>
                    }
                <?php else: ?>
                    "action_options": {
                        "request_type": false,
                        "package_type": false,
                        "print_position": true
                    }
                <?php endif; ?>
           }
       }
   }
</script>
