<?php /** @var $block \MyParcelBE\Magento\Block\Sales\ShipmentsAction */ ?>
<script type="text/x-magento-init">
   {
       ".page-footer": {
           "myparcelbe_massaction": {
                "has_api_key": <?= $block->hasApiKey();?>,
                "url": "<?= $block->getShipmentAjaxUrl(); ?>",
                "settings": <?= $block->getPrintSettings(); ?>,
                "button_present": false,
                "action_options": {
                    "request_type": true,
                    "package_type": true,
                    "print_position": true
                }
           }
        }
   }
</script>