<?php
/**
 * Overrides magento/module-sales/view/frontend/templates/email/shipment/track.phtml
 */

use MyParcelBE\Magento\Ui\Component\Listing\Column\TrackAndTrace;

/* @var \Magento\Framework\View\Element\Template $block */
$_shipment = $block->getShipment();

/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder();

if ($_shipment && $_order) :
    $trackCollection = $_order->getTracksCollection($_shipment->getId());

    if ($trackCollection) : ?>
        <br/>
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $_item) : ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?></td>
                    <td>
                        <?php
                        $trackingUrl = $block->getTrackingUrl();
                        // If the tracking number is equal to the "empty" value don't render a link.
                        if (! $trackingUrl || $_item->getNumber() === TrackAndTrace::VALUE_EMPTY) : ?>
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        <?php else : ?>
                            <a href="<?= $block->escapeUrl($trackingUrl->getUrl($_item)) ?>"
                               target="_blank">
                                <?= $block->escapeHtml($_item->getNumber()) ?>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif;
endif; ?>

